openapi: 3.0.1
info:
    title: imdb-api
    version: ''
paths:
    /actors/list-movies/{actorId}:
        get:
            description: >-
                TEST This endpoint will return a list of movies that Morgan Freeman (Actor ID
                `nm0000151`) has acted in. We'll list just 5 movies, because he's acted
                in over 153!
            operationId: actor_listMovies
            tags:
                - Actor
            parameters:
                - name: actorId
                  in: path
                  required: true
                  schema:
                      $ref: '#/components/schemas/ActorId'
                  examples:
                      Example1:
                          value: nm0000151
            responses:
                '200':
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Example1:
                                    value:
                                        - The Shawshank Redemption
                                        - The Power of One
                                        - Unforgiven
                                        - Outbreak
                                        - Se7en
            summary: List Movies for an Actor
    /movies/create-movie:
        post:
            description: Add a movie to the database
            operationId: movie_create
            tags:
                - Movie
            parameters: []
            responses:
                '200':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MovieId'
                            examples:
                                Example1:
                                    value: tt0111161
            summary: Create a Movie
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateMovieRequest'
                        examples:
                            Example1:
                                value:
                                    title: The Shawshank Redemption
                                    rating: 9.3
    /movies/{id}:
        get:
            description: Retrieve a movie from the database based on the ID
            operationId: movie_get
            tags:
                - Movie
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      $ref: '#/components/schemas/MovieId'
                  examples:
                      Example1:
                          value: tt9398640
                      Example2:
                          value: tt1234
            responses:
                '200':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Movie'
                            examples:
                                Example1:
                                    value:
                                        id: tt9398640
                                        title: 'Between Two Ferns: The Movie'
                                        rating: 6.1
                                        year: '2019'
                '404':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MovieId'
                            examples:
                                Example1:
                                    value: tt1234
            summary: Get a Movie by ID
        delete:
            operationId: movie_delete
            tags:
                - Movie
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      $ref: '#/components/schemas/MovieId'
                  examples:
                      Example1:
                          value: tt2294629
            responses:
                '204':
                    description: ''
                '404':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MovieId'
            summary: Delete a Movie by ID
        put:
            operationId: movie_update
            tags:
                - Movie
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      $ref: '#/components/schemas/MovieId'
                  examples:
                      Example1:
                          value: tt2294629
            responses:
                '204':
                    description: ''
                '404':
                    description: ''
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MovieId'
            summary: Update a Movie by ID
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateMovieRequest'
                        examples:
                            Example1:
                                value:
                                    year: '2019'
components:
    schemas:
        ActorId:
            title: ActorId
            type: string
            description: The unique identifier for an actor in the database
        MovieId:
            title: MovieId
            type: string
            description: The unique identifier for a movie in the database
        Movie:
            title: Movie
            type: object
            properties:
                id:
                    $ref: '#/components/schemas/MovieId'
                title:
                    type: string
                    example: 'Between Two Ferns: The Movie'
                rating:
                    type: number
                    format: double
                    description: The rating scale out of ten stars
                    example: 6.1
                year:
                    type: string
                    example: '2019'
            required:
                - id
                - title
                - rating
                - year
        CreateMovieRequest:
            title: CreateMovieRequest
            type: object
            properties:
                title:
                    type: string
                    example: The Shawshank Redemption
                rating:
                    type: number
                    format: double
                    example: 9.3
            required:
                - title
                - rating
        UpdateMovieRequest:
            title: UpdateMovieRequest
            type: object
            properties:
                title:
                    type: string
                    nullable: true
                rating:
                    type: number
                    format: double
                    nullable: true
                year:
                    type: string
                    nullable: true
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
servers:
    - url: https://sandbox.example.com
      description: Sandbox
