openapi: 3.0.1
info:
  title: imdb-api
  version: ''
paths: {}
components:
  schemas: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
servers:
  - url: https://sandbox.example.com
    description: Sandbox
